#!/bin/sh -xe

##
# This should be handled by Puppet;
# however, Puppet 3.8 does not support pkgng
ASSUME_ALWAYS_YES=YES /usr/sbin/pkg install sudo rsync
echo 'vagrant ALL=(ALL) NOPASSWD: ALL' >> /usr/local/etc/sudoers.d/vagrant
